### DISCUSSION TITLE
Styling the refinementList check boxes

### DISCUSSION THREAD

**Discussion by mikebhart** [algolia/instantsearch#4505] [General] [answered]
I'm customizing the refinementList widget. I'm having trouble styling the checkbox, the trouble is I cant see the classes used for the checkbox as I need to change color etc. Can you supply with the css code to access the refinementlist checkbox css class items so I can style it.

**Comment by Haroenv** [comment]
this is a duplicate of the menuSelect question, the documentation is on the same place. You can also use [inspect element](https://developers.google.com/web/tools/chrome-devtools/dom)

**Comment by mikebhart** [comment, marked as answer]
For anyone interested here's the css code to style the refinementlist checkboxes:-

```css
input[type=checkbox] {
	position: relative;
	cursor: pointer;
}

input[type=checkbox]::before {
	position: absolute;
	top: 0;
	left: 0;
	display: block;
	width: 16px;
	height: 16px;
	border: 1px solid orange;
	background-color: blue;
	content: "";
}

input[type=checkbox]:checked::after {
	position: absolute;
	top: 1px;
	left: 6px;
	display: block;
	width: 5px;
	height: 10px;
	border: solid blue;
	border-width: 0 2px 2px 0;
	content: "";
	-webkit-transform: rotate(45deg);
	-ms-transform: rotate(45deg);
	transform: rotate(45deg);
}
```
